# Generated by Django 5.0.4 on 2024-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenitites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_image', models.ImageField(upload_to='book_images/')),
                ('price', models.IntegerField()),
                ('emenities', models.ManyToManyField(to='book.emenitites')),
            ],
        ),
    ]
